#application: rp-optima
version: api-01
runtime: go
api_version: go1

handlers:
#- url: /static/(.*)
#  static_files: static/\1
#  upload: static/.*
#  http_headers:
#    Access-Control-Allow-Origin: .*

#- url: /.*
#  script: _go_app
#  secure: always

# rest api routes
- url: /api/(.*)
  script: _go_app
  secure: always

# static web fron-end routes
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html

# redirect to 'url + /index.html' url.
- url: /(.+)
  static_files: static/redirector.html
  upload: static/redirector.html

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html

#skip_files:
#  key.p12
#  cors-json-file.json
#  enable-cors.sh
#  ^(.*/)?\.bak$